apiVersion: v1
kind: Secret
metadata:
  name: sreesaaj-secrets
  namespace: sreesaaj
type: Opaque
stringData:
  postgres-password: "SreeSaaj@2024"
  jwt-secret: "sreesaaj-super-secret-key-2024-production"
  database-url-auth: "postgresql+asyncpg://sreesaaj:SreeSaaj@2024@postgres-auth:5432/auth_db"
  database-url-event: "postgresql+asyncpg://sreesaaj:SreeSaaj@2024@postgres-event:5432/event_db"
  database-url-inventory: "postgresql+asyncpg://sreesaaj:SreeSaaj@2024@postgres-inventory:5432/inventory_db"
  database-url-billing: "postgresql+asyncpg://sreesaaj:SreeSaaj@2024@postgres-billing:5432/billing_db"
  database-url-gallery: "postgresql+asyncpg://sreesaaj:SreeSaaj@2024@postgres-gallery:5432/gallery_db"
  database-url-menu: "postgresql+asyncpg://sreesaaj:SreeSaaj@2024@postgres-menu:5432/menu_db"
